      # ------------------------------------------------------------
      # Create DEV environment file
      #
      # Contains:
      #   1. Main System configuration
      #   2. Demo System configuration
      #   3. Stripe configuration
      #   4. Google Meet configuration
      #   5. Zoom configuration
      # ------------------------------------------------------------

      - name: Create development environment file
        env:

          # ----------------------------------------------------------
          # Main System
          # ----------------------------------------------------------

          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_SSL_CA: ${{ secrets.DB_SSL_CA }}
          APP_URL: ${{ secrets.APP_URL }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }}

          # ----------------------------------------------------------
          # Demo System
          # ----------------------------------------------------------

          DEMO_APP_URL: ${{ secrets.DEMO_APP_URL }}
          DEMO_DB_HOST: ${{ secrets.DEMO_DB_HOST }}
          DEMO_DB_PORT: ${{ secrets.DEMO_DB_PORT }}
          DEMO_DB_NAME: ${{ secrets.DEMO_DB_NAME }}
          DEMO_DB_USER: ${{ secrets.DEMO_DB_USER }}
          DEMO_DB_PASS: ${{ secrets.DEMO_DB_PASS }}
          DEMO_DB_SSL_CA: ${{ secrets.DEMO_DB_SSL_CA }}

          # ----------------------------------------------------------
          # Stripe
          # ----------------------------------------------------------

          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}

          # ----------------------------------------------------------
          # Google Meet
          # ----------------------------------------------------------

          DEV_GOOGLE_MEET_CLIENT_ID: ${{ secrets.DEV_GOOGLE_MEET_CLIENT_ID }}
          DEV_GOOGLE_MEET_CLIENT_SECRET: ${{ secrets.DEV_GOOGLE_MEET_CLIENT_SECRET }}
          DEV_GOOGLE_MEET_REDIRECT_URI: ${{ secrets.DEV_GOOGLE_MEET_REDIRECT_URI }}

          # ----------------------------------------------------------
          # Zoom
          # ----------------------------------------------------------

          DEV_ZOOM_ACCOUNT_ID: ${{ secrets.DEV_ZOOM_ACCOUNT_ID }}
          DEV_ZOOM_CLIENT_ID: ${{ secrets.DEV_ZOOM_CLIENT_ID }}
          DEV_ZOOM_CLIENT_SECRET: ${{ secrets.DEV_ZOOM_CLIENT_SECRET }}
          DEV_ZOOM_USER_EMAIL: ${{ secrets.DEV_ZOOM_USER_EMAIL }}

        run: |
          cat > .env <<EOF

          # ----------------------------------------------------------
          # Main System
          # ----------------------------------------------------------

          DB_HOST=$DB_HOST
          DB_PORT=$DB_PORT
          DB_NAME=$DB_NAME
          DB_USER=$DB_USER
          DB_PASS=$DB_PASS
          DB_SSL_CA=$DB_SSL_CA
          APP_URL=$APP_URL
          CRON_SECRET=$CRON_SECRET

          # ----------------------------------------------------------
          # Demo System
          # ----------------------------------------------------------

          DEMO_APP_URL=$DEMO_APP_URL
          DEMO_DB_HOST=$DEMO_DB_HOST
          DEMO_DB_PORT=$DEMO_DB_PORT
          DEMO_DB_NAME=$DEMO_DB_NAME
          DEMO_DB_USER=$DEMO_DB_USER
          DEMO_DB_PASS=$DEMO_DB_PASS
          DEMO_DB_SSL_CA=app/storage/certs/demo-ca.pem

          # ----------------------------------------------------------
          # Stripe
          # ----------------------------------------------------------

          STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY
          STRIPE_PUBLISHABLE_KEY=$STRIPE_PUBLISHABLE_KEY
          STRIPE_WEBHOOK_SECRET=$STRIPE_WEBHOOK_SECRET

          # ----------------------------------------------------------
          # Google Meet
          # ----------------------------------------------------------

          GOOGLE_MEET_CLIENT_ID=$DEV_GOOGLE_MEET_CLIENT_ID
          GOOGLE_MEET_CLIENT_SECRET=$DEV_GOOGLE_MEET_CLIENT_SECRET
          GOOGLE_MEET_REDIRECT_URI=$DEV_GOOGLE_MEET_REDIRECT_URI

          # ----------------------------------------------------------
          # Zoom
          # ----------------------------------------------------------

          ZOOM_ACCOUNT_ID=$DEV_ZOOM_ACCOUNT_ID
          ZOOM_CLIENT_ID=$DEV_ZOOM_CLIENT_ID
          ZOOM_CLIENT_SECRET=$DEV_ZOOM_CLIENT_SECRET
          ZOOM_USER_EMAIL=$DEV_ZOOM_USER_EMAIL

          EOF