name: Deploy to IONOS Demo

on:
  push:
    branches:
      - main

jobs:
  deploy-demo:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy application files to IONOS Demo
        env:
          SFTP_HOST: ${{ secrets.DEMO_SFTP_HOST }}
          SFTP_PORT: ${{ secrets.DEMO_SFTP_PORT }}
          SFTP_USERNAME: ${{ secrets.DEMO_SFTP_USERNAME }}
          SFTP_PASSWORD: ${{ secrets.DEMO_SFTP_PASSWORD }}
          SFTP_PATH: ${{ secrets.DEMO_SFTP_PATH }}
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

          lftp -c "
            set sftp:auto-confirm yes;
            set net:max-retries 2;
            set net:timeout 20;
            set sftp:connect-program 'ssh -a -x -o StrictHostKeyChecking=no';
            open -u $SFTP_USERNAME,$SFTP_PASSWORD sftp://$SFTP_HOST:$SFTP_PORT;
            mirror --reverse --delete --verbose \
              --exclude-glob .git \
              --exclude-glob .github \
              --exclude-glob .env \
              --exclude-glob .htaccess \
              --exclude-glob .htpasswd \
              --exclude-glob storage/logs \
              --exclude-glob app/storage/certs/ca.pem \
              --exclude-glob app/storage/certs/demo-ca.pem \
              ./ \"$SFTP_PATH\";
            bye
          "

      - name: Create Demo environment file
        env:
          SFTP_HOST: ${{ secrets.DEMO_SFTP_HOST }}
          SFTP_PORT: ${{ secrets.DEMO_SFTP_PORT }}
          SFTP_USERNAME: ${{ secrets.DEMO_SFTP_USERNAME }}
          SFTP_PASSWORD: ${{ secrets.DEMO_SFTP_PASSWORD }}
          SFTP_PATH: ${{ secrets.DEMO_SFTP_PATH }}

          DEMO_APP_URL: ${{ secrets.DEMO_APP_URL }}
          DEMO_DB_HOST: ${{ secrets.DEMO_DB_HOST }}
          DEMO_DB_PORT: ${{ secrets.DEMO_DB_PORT }}
          DEMO_DB_NAME: ${{ secrets.DEMO_DB_NAME }}
          DEMO_DB_USER: ${{ secrets.DEMO_DB_USER }}
          DEMO_DB_PASS: ${{ secrets.DEMO_DB_PASS }}
          DEMO_DB_SSL_CA: ${{ secrets.DEMO_DB_SSL_CA }}

        run: |
          cat > demo.env <<EOF
          DEMO_APP_URL=$DEMO_APP_URL
          DEMO_DB_HOST=$DEMO_DB_HOST
          DEMO_DB_PORT=$DEMO_DB_PORT
          DEMO_DB_NAME=$DEMO_DB_NAME
          DEMO_DB_USER=$DEMO_DB_USER
          DEMO_DB_PASS=$DEMO_DB_PASS
          DEMO_DB_SSL_CA=$DEMO_DB_SSL_CA
          EOF

          lftp -c "
            set sftp:auto-confirm yes;
            set net:max-retries 2;
            set net:timeout 20;
            set sftp:connect-program 'ssh -a -x -o StrictHostKeyChecking=no';
            open -u $SFTP_USERNAME,$SFTP_PASSWORD sftp://$SFTP_HOST:$SFTP_PORT;
            put -O \"$SFTP_PATH\" demo.env;
            bye
          "

          rm -f demo.env